// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    ConfirmDialog: typeof import('./src/components/overlays/ConfirmDialog.vue')['default']
    ConfirmLeaveDialog: typeof import('./src/components/overlays/ConfirmLeaveDialog.vue')['default']
    ErrorDialog: typeof import('./src/components/overlays/ErrorDialog.vue')['default']
    ErrorOverlay: typeof import('./src/components/overlays/ErrorOverlay.vue')['default']
    FormCard: typeof import('./src/components/forms/FormCard.vue')['default']
    Lightbox: typeof import('./src/components/Lightbox.vue')['default']
    NFO: typeof import('./src/components/NFO.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideDownTransition: typeof import('./src/components/transitions/SlideDownTransition.vue')['default']
    SlideTransition: typeof import('./src/components/transitions/SlideTransition.vue')['default']
    SplashScreen: typeof import('./src/components/overlays/SplashScreen.vue')['default']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
    Switch: typeof import('./src/components/forms/Switch.vue')['default']
    Textarea: typeof import('./src/components/forms/Textarea.vue')['default']
    TextField: typeof import('./src/components/forms/TextField.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
    WebsocketDisconnected: typeof import('./src/components/overlays/WebsocketDisconnected.vue')['default']
  }
}
